let parser = (
  disabled:bool = false
)
{
  ASimUserManagementActivityLogs
  | where not(disabled)
  | project-rename
      EventUid = _ItemId
  | extend          
      EventSchema = "UserManagement",
      DvcScopeId = iff(isempty(DvcScopeId), _SubscriptionId, DvcScopeId)
  //  -- Aliases
  | extend
      EventEndTime = iff (isnull(EventEndTime), TimeGenerated, EventEndTime),
      EventStartTime = iff (isnull(EventEndTime), TimeGenerated, EventStartTime),
      Dvc = coalesce (DvcFQDN, DvcHostname, DvcIpAddr, DvcId, _ResourceId),
      Rule = coalesce(RuleName, tostring(RuleNumber)),
      User = ActorUsername,
      Hostname = DvcHostname,
      IpAddr = SrcIpAddr,
      Src = coalesce (SrcHostname,SrcIpAddr, SrcDvcId),
      UpdatedPropertyName = EventSubType
  | project-away
      TenantId,
      SourceSystem,
      _SubscriptionId,
      _ResourceId
};
parser (disabled = disabled)
