let parser=(disabled:bool=false) 
{
  ASimAuthenticationEventLogs  | where not(disabled)
    | extend
        User =  TargetUsername,
        Src = coalesce (SrcDvcId, SrcHostname, SrcIpAddr),
        IpAddr=SrcIpAddr,
        LogonTarget= coalesce (TargetAppName, TargetUrl, TargetHostname),
        Dvc=EventVendor,
        Application=TargetAppName,
        Dst = coalesce (TargetDvcId,TargetHostname, TargetIpAddr, TargetAppId,TargetAppName), 
        Rule = coalesce(RuleName, tostring(RuleNumber)),
        EventStartTime = TimeGenerated,
        EventEndTime = TimeGenerated,
        EventSchema = "Authentication"
    | project-rename
        EventUid = _ItemId
  | project-away TenantId, SourceSystem, _ResourceId, _SubscriptionId
};
parser  (disabled=disabled)
