source
| extend properties = parse_json(properties)
| project
	TimeGenerated = todatetime(['time']),
	Protocol = tostring(properties.Protocol),
	SourceIp = tostring(properties.SourceIp),
	DestinationPort = toint(properties.DestinationPort),
	Fqdn = tostring(properties.Fqdn),
	TargetUrl = tostring(properties.Url),
	Action = tostring(properties.Action),
	Policy = tostring(properties.Policy),
	RuleCollectionGroup = tostring(properties.RuleCollectionGroup),
	RuleCollection = tostring(properties.RuleCollection),
	Rule = tostring(properties.Rule),
	ActionReason = tostring(properties.ActionReason),
	ApplicationRuleCount = toint(properties.ApplicationRuleCount)