let parser=(disabled:bool=false) 
{
  ASimAuditEventLogs  | where not(disabled)
    | extend EventSchema = "AuditEvent"
    | project-rename
        EventUid = _ItemId
    | extend
        Value	= NewValue,
        User =  ActorUsername,
        Application =  TargetAppName,
        Dst = coalesce (TargetDvcId, TargetHostname, TargetIpAddr, TargetAppId, TargetAppName),
        Dvc = coalesce (DvcFQDN, DvcHostname, DvcIpAddr, DvcId, _ResourceId, strcat (EventVendor,'/', EventProduct)), 
        Rule=RuleName,
        IpAddr=SrcIpAddr,
        EventStartTime = TimeGenerated,
        EventEndTime = TimeGenerated,
        Src = coalesce (SrcFQDN, SrcHostname, SrcIpAddr, SrcDvcId)
    | project-away
        _ResourceId, _SubscriptionId
};
parser  (disabled=disabled)