source
| extend Properties = parse_json(tostring(properties))
| extend Type = tostring("SynapseIntegrationPipelineRunsEnded")
| project
    TimeGenerated = todatetime(["time"]),
    OperationName = operationName,
    Category = category,
    CorrelationId = correlationId,
    Level = level,
    Location = location,
    Tags = todynamic(tags),
    Status = status,
    UserProperties = todynamic(Properties["UserProperties"]),
    Annotations = todynamic(Properties["Annotations"]),
    Start = todatetime(start),
    End = todatetime(end),
    PipelineName = pipelineName,
    RunId = runId,
    Predecessors = todynamic(Properties["Predecessors"]),
    Parameters = todynamic(Properties["Parameters"]),
    SystemParameters = todynamic(Properties["SystemParameters"]),
    Type = Type,
    PipelineTenantId = ''
