source
| extend Properties = parse_json(tostring(properties))
| extend Type = tostring("SynapseIntegrationActivityRunsEnded")
| project
    TimeGenerated = todatetime(["time"]),
    OperationName = operationName,
    Category = category,
    CorrelationId = correlationId,
    Level = level,
    Location = location,
    Tags = todynamic(tags),
    Status = status,
    UserProperties = todynamic(Properties["UserProperties"]),
    Annotations = todynamic(Properties["Annotations"]),
    Start = todatetime(start),
    End = todatetime(end),
    ActivityName = activityName,
    ActivityRunId = activityRunId,
    PipelineRunId = pipelineRunId,
    EffectiveIntegrationRuntime = pipelineName,
    ActivityType = activityType,
    PipelineName = pipelineName
