source
| extend props = parse_json(properties)
| project
    TimeGenerated = todatetime(["time"]),
    OperationName = operationName,
    OperationVersion = operationVersion,
    Category = category,
    ResultType = resultType,
    ResultSignature = resultSignature,
    ResultDescription = resultDescription,
    DurationMs = toint(durationMs),
    CallerIpAddress = callerIpAddress,
    CorrelationId = correlationId,
    Level = level,
    URI = uri,
    Identity = tostring(props.identity),
    Scopes = parse_json(props.scopes),
    SdkType = tostring(props.sdkType),
    PlatformType = tostring(props.platformType)
