source
| extend parsedMetrics = parse_json(metrics)
| extend parsedTags = parse_json(tags)
| mvexpand parsedMetrics
| extend nameValuePair = tostring(parsedMetrics)
| extend nameValueDelim = indexof(nameValuePair, ":")
| where isnotnull(nameValueDelim)
| extend MetricName = substring(nameValuePair, 2, nameValueDelim - 3)
| extend MetricValue = todouble(substring(nameValuePair, nameValueDelim + 1, strlen(nameValuePair) - nameValueDelim - 2))
| where isnotnull(MetricValue)
| project TimeGenerated = FluentdIngestTimestamp, Entity = entity, EntityType = entitytype, MetricName, MetricValue, Tags = parsedTags, HostName = hostName, ClusterName = clusterName, ClusterType = clusterType, QuerySubmissionTime = tolong(QUERY_SUBMITTED), QueryCompletionTime = tolong(QUERY_COMPLETED), Domain = domain, RequestUser = primaryfilters_requestuser_0, ExecutionMode = primaryfilters_executionmode_0, User = primaryfilters_user_0, Queue = primaryfilters_queue_0, TablesRead = primaryfilters_tablesread_0, ClientIpAddress = otherinfo_CLIENT_IP_ADDRESS, IsTez = tobool(otherinfo_TEZ), IsMapReduce = tobool(otherinfo_MAPRED), ThreadName = otherinfo_THREAD_NAME, HiveInstanceType = otherinfo_HIVE_INSTANCE_TYPE, SessionId = otherinfo_SESSION_ID, OperationName = operationName, CorrelationId = correlationId