source
| extend parsedMetrics = parse_json(metrics)
| extend parsedTags = parse_json(tags)
| mvexpand parsedMetrics
| extend nameValuePair = tostring(parsedMetrics)
| extend nameValueDelim = indexof(nameValuePair, ":")
| where isnotnull(nameValueDelim)
| extend MetricName = substring(nameValuePair, 2, nameValueDelim - 3)
| extend MetricValue = todouble(substring(nameValuePair, nameValueDelim + 1, strlen(nameValuePair) - nameValueDelim - 2))
| where isnotnull(MetricValue)
| project TimeGenerated = FluentdIngestTimestamp, MetricNamespace = name, MetricName, MetricValue, Tags = parsedTags, HostName = hostName, ClusterName = clusterName, ClusterType = clusterType, OperationName = operationName, CorrelationId = correlationId