HDInsightHBaseLogs 
//| where ClusterName == '<your cluster name>' // remove the preceding "//" and specify your cluster name to see its logs
| where TimeGenerated > ago(24h)
| where LogType == 'HBaseMasterLog' //can set which type of logs you want to see (ex: HBaseMasterLog, HBaseRegionServerLog, etc.)
| where LogLevel == 'ERROR' //set which LogLevels you want to see (ex: "ERROR","WARN","INFO)
| take 10