// Latest scorecard metadata for a given feature
// set the feature flag name to query
let QueryFeature = "MyFeatureFlag";
OEWExperimentAssignmentSummary
| where FeatureName == QueryFeature
| summarize LastAssignmentTimestamp=max(LastAssignmentTimestamp), Variants=make_set(Variant, 1000) by AllocationId
| summarize arg_max(LastAssignmentTimestamp, *)
| join kind=inner OEWExperimentScorecards on AllocationId
| summarize arg_max(TimeGenerated, ScorecardId)
| project
    FeatureName, AllocationId, Variants,
    ScorecardId, AnalysisStartTime, AnalysisEndTime, Insights