let parser = (
  disabled:bool = false
)
{
  ASimDhcpEventLogs
  | where not(disabled)
  | project-rename
      EventUid = _ItemId
  | extend          
      EventSchema = "DhcpEvent",
      DvcScopeId = iff(isempty(DvcScopeId), _SubscriptionId, DvcScopeId)
  //  -- Aliases
  | extend
      EventEndTime = iff (isnull(EventEndTime), TimeGenerated, EventEndTime),
      EventStartTime = iff (isnull(EventEndTime), TimeGenerated, EventStartTime),
      Dvc = coalesce (DvcFQDN, DvcHostname, DvcIpAddr, DvcId, _ResourceId),
      Rule = coalesce(RuleName, tostring(RuleNumber)),
      SessionId = DhcpSessionId,
      Duration = DhcpSessionDuration,
      Src = coalesce (SrcFQDN, SrcHostname, SrcIpAddr, SrcDvcId),
      User = SrcUsername,
      IpAddr = SrcIpAddr,
      Hostname = SrcHostname
};
parser (disabled = disabled)
