((AgriFoodFarmManagementLogs | where FarmerId != "" | summarize AgriFoodFarmManagementLogsCount=count() by FarmerId))
| join kind=fullouter (( AgriFoodSatelliteLogs | where FarmerId != "" | summarize AgriFoodSatelliteLogsCount=count() by FarmerId)) on FarmerId
| join kind=fullouter (( AgriFoodWeatherLogs | where FarmerId != "" | summarize AgriFoodWeatherLogsCount=count() by FarmerId)) on FarmerId
| join kind=fullouter (( AgriFoodJobProcessedLogs | where FarmerId != "" | summarize AgriFoodJobProcessedLogsCount=count() by FarmerId)) on FarmerId
| join kind=fullouter (( AgriFoodFarmOperationLogs | where FarmerId != "" | summarize AgriFoodFarmOperationLogsCount=count() by FarmerId)) on FarmerId
| join kind=fullouter (( AgriFoodInsightLogs | where FarmerId != "" | summarize AgriFoodInsightLogsCount=count() by FarmerId)) on FarmerId
| join kind=fullouter (( AgriFoodProviderAuthLogs | where FarmerId != "" | summarize AgriFoodProviderAuthLogsCount=count() by FarmerId)) on FarmerId
| join kind=fullouter (( AgriFoodModelInferenceLogs | where FarmerId != "" | summarize AgriFoodModelInferenceLogsCount=count() by FarmerId)) on FarmerId
| project FarmerId = coalesce(FarmerId, FarmerId1, FarmerId2, FarmerId3, FarmerId4, FarmerId5, FarmerId6, FarmerId7), AgriFoodFarmManagementLogsCount, AgriFoodSatelliteLogsCount, AgriFoodWeatherLogsCount, AgriFoodJobProcessedLogsCount, AgriFoodFarmOperationLogsCount, AgriFoodInsightLogsCount, AgriFoodProviderAuthLogsCount, AgriFoodModelInferenceLogsCount
| take 100 
