source
| project
	TimeGenerated = todatetime(['time']),
	OperationName = tostring(split(operationName, '/')[2]),
	ResultSignature = resultSignature,
	ResultDescription = resultDescription,
	ClientIdentity = tostring(identity.clientIdentity),
	SessionName = tostring(properties.sessionName),
	Protocol = tostring(properties.protocol),
	Qos = toint(properties.qos),
	TopicName = tostring(properties.topicName)
