VCoreMongoRequests
// Time range filter:  | where TimeGenerated between (StartTime .. EndTime)
// Resource id filter: | where _ResourceId == "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/my-resource-group-name/providers/microsoft.documentdb/mongoclusters/my-cluster-name"
| project TimeGenerated, DurationBin=tostring(bin(DurationMs, 5))
| summarize count() by bin(TimeGenerated, 1m), tostring(DurationBin)
