source
| extend properties = parse_json(properties)
| project
    TimeGenerated = todatetime(['time']),
    Location = location,
    OperationName = operationName,
    CacheName = tostring(properties.tenant),
    ConnectedClients = todynamic(properties.connectedClients),
    RoleInstance = tostring(properties.roleInstance)
| mvexpand ConnectedClients 
| extend 
    ClientIp = tostring(ConnectedClients['ip']),
    PrivateLinkIpv6 = tostring(ConnectedClients['privateLinkIpv6']),
    ClientCount = toint(ConnectedClients['count'])
| project-away ConnectedClients
