source 
| extend 
    TimeGenerated = datetime(1970-01-01) + tolong(start) * 1s 
| project 
    TimeGenerated, 
    Version = tostring(version), 
    AccountId = tostring(['account-id']), 
    InterfaceId = tostring(['interface-id']), 
    SourceAddress = tostring(srcaddr), 
    DestinationAddress = tostring(dstaddr), 
    SourcePort = tostring(srcport), 
    DestinationPort = tostring(dstport), 
    Protocol = tostring(protocol), 
    Packets = tostring(packets), 
    Bytes = tostring(bytes), 
    SStartTime = datetime(1970-01-01) + tolong(start) * 1s, 
    EndTime = datetime(1970-01-01) + tolong(end) * 1s, 
    Action = tostring(action), 
    LogStatus = tostring(['log-status']),
    LogType=tostring('GLBFlowLogs')