let recordTypeMap = parse_json('{ '
' "1": "ExchangeAdmin", '
' "2": "ExchangeItem", '
' "3": "ExchangeItemGroup", '
' "4": "SharePoint", '
' "5": "SyntheticProbe", '
' "6": "SharePointFileOperation", '
' "7": "OneDrive", '
' "8": "AzureActiveDirectory", '
' "9": "AzureActiveDirectoryAccountLogon", '
' "10": "DataCenterSecurityCmdlet", '
' "11": "ComplianceDLPSharePoint", '
' "12": "Sway", '
' "13": "ComplianceDLPExchange", '
' "14": "SharePointSharingOperation", '
' "15": "AzureActiveDirectoryStsLogon", '
' "16": "SkypeForBusinessPSTNUsage", '
' "17": "SkypeForBusinessUsersBlocked", '
' "18": "SecurityComplianceCenterEOPCmdlet", '
' "19": "ExchangeAggregatedOperation", '
' "20": "PowerBIAudit", '
' "21": "CRM", '
' "22": "Yammer", '
' "23": "SkypeForBusinessCmdlets", '
' "24": "Discovery", '
' "25": "MicrosoftTeams", '
' "28": "ThreatIntelligence", '
' "29": "MailSubmission", '
' "30": "MicrosoftFlow", '
' "31": "AeD", '
' "32": "MicrosoftStream", '
' "33": "ComplianceDLPSharePointClassification", '
' "34": "ThreatFinder", '
' "35": "Project", '
' "36": "SharePointListOperation", '
' "37": "SharePointCommentOperation", '
' "38": "DataGovernance", '
' "39": "Kaizala", '
' "40": "SecurityComplianceAlerts", '
' "41": "ThreatIntelligenceUrl", '
' "42": "SecurityComplianceInsights", '
' "43": "MIPLabel", '
' "44": "WorkplaceAnalytics", '
' "45": "PowerAppsApp", '
' "46": "PowerAppsPlan", '
' "47": "ThreatIntelligenceAtpContent", '
' "48": "LabelContentExplorer", '
' "49": "TeamsHealthcare", '
' "50": "ExchangeItemAggregated", '
' "51": "HygieneEvent", '
' "52": "DataInsightsRestApiAudit", '
' "53": "InformationBarrierPolicyApplication", '
' "54": "SharePointListItemOperation", '
' "55": "SharePointContentTypeOperation", '
' "56": "SharePointFieldOperation", '
' "57": "MicrosoftTeamsAdmin", '
' "58": "HRSignal", '
' "59": "MicrosoftTeamsDevice", '
' "60": "MicrosoftTeamsAnalytics", '
' "61": "InformationWorkerProtection", '
' "62": "Campaign", '
' "63": "DLPEndpoint", '
' "64": "AirInvestigation", '
' "65": "Quarantine", '
' "66": "MicrosoftForms", '
' "67": "ApplicationAudit", '
' "68": "ComplianceSupervisionExchange", '
' "69": "CustomerKeyServiceEncryption", '
' "70": "OfficeNative", '
' "71": "MipAutoLabelSharePointItem", '
' "72": "MipAutoLabelSharePointPolicyLocation", '
' "73": "MicrosoftTeamsShifts", '
' "74": "SecureScore", '
' "75": "MipAutoLabelExchangeItem", '
' "76": "CortanaBriefing", '
' "77": "Search", '
' "78": "WDATPAlerts", '
' "79": "PowerPlatformAdminDlp", '
' "80": "PowerPlatformAdminEnvironment", '
' "81": "MDATPAudit", '
' "82": "SensitivityLabelPolicyMatch", '
' "83": "SensitivityLabelAction", '
' "84": "SensitivityLabeledFileAction", '
' "85": "AttackSim", '
' "86": "AirManualInvestigation", '
' "87": "SecurityComplianceRBAC", '
' "88": "UserTraining", '
' "89": "AirAdminActionInvestigation", '
' "90": "MSTIC", '
' "91": "PhysicalBadgingSignal", '
' "92": "TeamsEasyApprovals", '
' "93": "AipDiscover", '
' "94": "AipSensitivityLabelAction", '
' "95": "AipProtectionAction", '
' "96": "AipFileDeleted", '
' "97": "AipHeartBeat", '
' "98": "MCASAlerts", '
' "99": "OnPremisesFileShareScannerDlp", '
' "100": "OnPremisesSharePointScannerDlp", '
' "101": "ExchangeSearch", '
' "102": "SharePointSearch", '
' "103": "PrivacyDataMinimization", '
' "104": "LabelAnalyticsAggregate", '
' "105": "MyAnalyticsSettings", '
' "106": "SecurityComplianceUserChange", '
' "107": "ComplianceDLPExchangeClassification", '
' "108": "ComplianceDLPEndpoint", '
' "109": "MipExactDataMatch", '
' "110": "MSDEResponseActions", '
' "111": "MSDEGeneralSettings", '
' "112": "MSDEIndicatorsSettings", '
' "113": "MS365DCustomDetection", '
' "114": "MSDERolesSettings", '
' "115": "MAPGAlerts", '
' "116": "MAPGPolicy", '
' "117": "MAPGRemediation", '
' "118": "PrivacyRemediationAction", '
' "119": "PrivacyDigestEmail", '
' "120": "MipAutoLabelSimulationProgress", '
' "121": "MipAutoLabelSimulationCompletion", '
' "122": "MipAutoLabelProgressFeedback", '
' "123": "DlpSensitiveInformationType", '
' "124": "MipAutoLabelSimulationStatistics", '
' "125": "LargeContentMetadata", '
' "126": "Microsoft365Group", '
' "127": "CDPMlInferencingResult", '
' "128": "FilteringMailMetadata", '
' "129": "CDPClassificationMailItem", '
' "130": "CDPClassificationDocument", '
' "131": "OfficeScriptsRunAction", '
' "132": "FilteringPostMailDeliveryAction", '
' "133": "CDPUnifiedFeedback", '
' "134": "TenantAllowBlockList", '
' "135": "ConsumptionResource", '
' "136": "HealthcareSignal", '
' "138": "DlpImportResult", '
' "139": "CDPCompliancePolicyExecution", '
' "140": "MultiStageDisposition", '
' "141": "PrivacyDataMatch", '
' "142": "FilteringDocMetadata", '
' "143": "FilteringEmailFeatures", '
' "144": "PowerBIDlp", '
' "145": "FilteringUrlInfo", '
' "146": "FilteringAttachmentInfo", '
' "147": "CoreReportingSettings", '
' "148": "ComplianceConnector", '
' "149": "PowerPlatformLockboxResourceAccessRequest", '
' "150": "PowerPlatformLockboxResourceCommand", '
' "151": "CDPPredictiveCodingLabel", '
' "152": "CDPCompliancePolicyUserFeedback", '
' "153": "WebpageActivityEndpoint", '
' "154": "OMEPortal", '
' "155": "CMImprovementActionChange", '
' "156": "FilteringUrlClick" , '
' "157": "MipLabelAnalyticsAuditRecord", '
' "158": "FilteringEntityEvent", '
' "159": "FilteringRuleHits", '
' "160": "FilteringMailSubmission", '
' "161": "LabelExplorer", '
' "162": "MicrosoftManagedServicePlatform", '
' "163": "PowerPlatformServiceActivity", '
' "164": "ScorePlatformGenericAuditRecord", '
' "165": "FilteringTimeTravelDocMetadata", '
' "166": "Alert", '
' "167": "AlertStatus", '
' "168": "AlertIncident", '
' "169": "IncidentStatus", '
' "170": "Case", '
' "171": "CaseInvestigation", '
' "172": "RecordsManagement", '
' "173": "PrivacyRemediation", '
' "174": "DataShareOperation", '
' "175": "CdpDlpSensitive", '
' "176": "EHRConnector", '
' "177": "FilteringMailGradingResult", '
' "178": "PublicFolder", '
' "179": "PrivacyTenantAuditHistoryRecord", '
' "180": "AipScannerDiscoverEvent", '
' "181": "EduDataLakeDownloadOperation", '
' "182": "M365ComplianceConnector", '
' "183": "MicrosoftGraphDataConnectOperation", '
' "184": "MicrosoftPurview", '
' "185": "FilteringEmailContentFeatures", '
' "186": "PowerPagesSite", '
' "187": "PowerAppsResource" '
' }');
let userTypeMap = parse_json('{ '
' "0": "Regular", '
' "1": "Reserved" ,'
' "2": "Admin", '
' "3": "DcAdmin", '
' "4": "System", '
' "5": "Application", '
' "6": "ServicePrincipal", '
' "7": "CustomPolicy", '
' "8": "SystemPolicy" '
' }');
let scopeMap = parse_json('{ '
' "0": "Online", '
' "1": "Onprem" '
' }');
let targetLocationMap = parse_json('{ '
' "0": "Unknown", '
' "1": "Local" ,'
' "2": "Remote" ,'
' "3": "Removable" ,'
' "4": "Cloud" ,'
' "5": "FileShare" '
' }');
let actionSourceMap = parse_json('{ '
' "0": "None", '
' "1": "Default", '
' "2": "Automatic" ,'
' "3": "Manual" ,'
' "4": "Recommended" '
' }');
let labelEventTypeMap = parse_json('{ '
' "0": "None" ,'
' "1": "LabelUpgraded", '
' "2": "LabelDowngraded" ,'
' "3": "LabelRemoved" ,'
' "4": "LabelChangedSameOrder" ,'
' "5": "LabelApplied" ,'
' "6": "LabelChanged" '
' }');
let actionSourceDetailMap = parse_json('{ '
' "0": "None", '
' "1": "AutoByPolicyMatch", '
' "2": "AutoByReplyOrForward", '
' "3": "AutoByInheritance", '
' "4": "AutoByDeploymentPipeline", '
' "5": "PublicAPI", '
' "6": "AutoByLibraryDefault" '
' }');
let platformMap =  parse_json('{'
' "0": "Unknown" ,'
' "1": "Windows", '
' "2": "Mac" ,'
' "3": "iOS" ,'
' "4": "Android" ,'
' "5": "WebBrowser" '
' }');
let protectionEventTypeMap =  parse_json('{'
' "0": "Unchanged" ,'
' "1": "NewProtection", '
' "2": "ChangeProtection" ,'
' "3": "RemoveProtection" '
' }');
let sensitivityLabelAuditRecordProtectionEventTypeMap =  parse_json('{'
' "0": "Unchanged" ,'
' "1": "Applied", '
' "2": "Changed" ,'
' "3": "Removed" '
' }');
let protectionTypeMap =  parse_json('{'
' "0": "None" ,'
' "1": "Template", '
' "2": "DoNotForward" ,'
' "3": "EncryptOnly" ,'
' "4": "Custom" '
' }');
source
| extend
    commonPlatformName = tostring(platformMap[tostring(Common["Platform"])]),
    userTypeName = tostring(userTypeMap[tostring(UserType)]),
    scopeName = tostring(scopeMap[tostring(Scope)]),
    platformName = tostring(platformMap[tostring(Platform)]),
    targetLocationName = tostring(targetLocationMap[tostring(TargetLocation)]),
    labelEventTypeName = tostring(labelEventTypeMap[tostring(SensitivityLabelEventData["LabelEventType"])]),
    actionSourceName = tostring(actionSourceMap[tostring(SensitivityLabelEventData["ActionSource"])]),
    actionSourceDetailName = tostring(actionSourceDetailMap[tostring(SensitivityLabelEventData["ActionSourceDetail"])]),
    sensitivityLabelAuditRecordProtectionEventTypeName = tostring(sensitivityLabelAuditRecordProtectionEventTypeMap[tostring(ProtectionEventType)]),
    currentProtectionTypeName = tostring(protectionTypeMap[tostring(CurrentProtectionType["protectionType"])]),
    previousProtectionTypeName = tostring(protectionTypeMap[tostring(PreviousProtectionType["protectionType"])])
| project
    Id = tostring(Id),
    RecordType = toint(RecordType),
    RecordTypeName = tostring(recordTypeMap[tostring(RecordType)]),
    TimeGenerated = todatetime(CreationTime),
    Operation = tostring(Operation),
    OrganizationId = tostring(OrganizationId),
    UserType = iif(isnotempty(userTypeName), userTypeName, tostring(UserType)),
    UserKey = tostring(UserKey),
    Workload = tostring(Workload),
    ResultStatus = tostring(ResultStatus),
    ObjectId = tostring(ObjectId),
    UserId = tostring(UserId),
    ClientIP = tostring(ClientIP),
    Scope = iif(isnotempty(scopeName), scopeName, tostring(Scope)),
    AppAccessContext = todynamic(AppAccessContext),
    Application = tostring(Application),
    Platform = iif(isnotempty(platformName), platformName, iif(isnotempty(commonPlatformName), commonPlatformName, tostring(Platform))),
    DeviceName = tostring(DeviceName),
    EmailInfo = todynamic(EmailInfo),
    CurrentProtectionTypeName = currentProtectionTypeName,
    PreviousProtectionTypeName = previousProtectionTypeName,
    ContentType = tostring(ContentType),
    TargetLocation = iif(isnotempty(targetLocationName), targetLocationName, tostring(TargetLocation)),
    IrmContentId = tostring(IrmContentId),
    SensitivityLabelId = iif(isnotempty(LabelId), tostring(LabelId), tostring(SensitivityLabelEventData["SensitivityLabelId"])),
    SensitivityLabelOwnerEmail = tostring(SensitivityLabelEventData["SensitivityLabelOwnerEmail"]),
    OldSensitivityLabelId = tostring(SensitivityLabelEventData["OldSensitivityLabelId"]),
    OldSensitivityLabelOwnerEmail = tostring(SensitivityLabelEventData["OldSensitivityLabelOwnerEmail"]),
    SensitivityLabelPolicyId = tostring(SensitivityLabelEventData["SensitivityLabelPolicyId"]),
    LabelEventType = iif(isnotempty(labelEventTypeName), labelEventTypeName, tostring(SensitivityLabelEventData["LabelEventType"])),
    ActionSource =  iif(isnotempty(actionSourceName), actionSourceName, tostring(SensitivityLabelEventData["ActionSource"])),
    ActionSourceDetail = iif(isnotempty(actionSourceDetailName), actionSourceDetailName, tostring(SensitivityLabelEventData["ActionSourceDetail"])),
    JustificationText = tostring(SensitivityLabelEventData["JustificationText"]),
    ProtectionEventTypeName = iif(isnotempty(ProtectionEventType), sensitivityLabelAuditRecordProtectionEventTypeName, tostring(protectionEventTypeMap[tostring(ProtectionEventData["ProtectionEventType"])])),
    DataState = tostring(DataState),
    SensitiveInfoTypeData = todynamic(SensitiveInfoTypeData),
    ProtectionEventData = todynamic(ProtectionEventData),
    Common = todynamic(Common),
    Sender = tostring(Sender),
    Receivers = todynamic(Receivers),
    ItemName = tostring(ItemName),
    LabelName = tostring(LabelName),
    LabelAction = tostring(LabelAction),
    LabelAppliedDateTime = todatetime(LabelAppliedDateTime),
    ApplicationMode = tostring(ApplicationMode),
    ExchangeMetaData = todynamic(ExchangeMetaData),
    ConditionMatch = todynamic(ConditionMatch),
    RuleActions = todynamic(RuleActions),
    WorkLoadItemId = tostring(WorkLoadItemId),
    OverriddenActions = todynamic(OverriddenActions),
    SensitiveInfoDetectionIsIncluded = tobool(SensitiveInfoDetectionIsIncluded),
    IsViewableByExternalUsers = tobool(IsViewableByExternalUsers),
    OverRideType = tostring(OverRideType),
    ItemCreationTime = todatetime(ItemCreationTime),
    ItemLastModifiedTime = todatetime(ItemLastModifiedTime),
    ItemSize = tostring(ItemSize),
    OverRideReason = tostring(OverRideReason),
    CorrelationId = tostring(CorrelationId),
    ScopedLocationId = tostring(ScopedLocationId),
    MachineName = tostring(MachineName),
    PolicyId = tostring(PolicyId),
    PolicyName = tostring(PolicyName),
    PolicyVersion = tostring(PolicyVersion),
    ExecutionRuleId = tostring(ExecutionRuleId),
    ExecutionRuleName = tostring(ExecutionRuleName),
    ExecutionRuleVersion = tostring(ExecutionRuleVersion),
    RuleMode = tostring(RuleMode),
    Severity = tostring(Severity),
    LabelVersion = tostring(LabelVersion),
    MgtRuleId = tostring(MgtRuleId),
    SharePointMetaData = todynamic(SharePointMetaData),
    CurrentProtectionType = todynamic(CurrentProtectionType),
    PreviousProtectionType = todynamic(PreviousProtectionType),
    SensitivityLabelEventFailureData = todynamic(SensitivityLabelEventFailureData),
    AutoSensitivityLabelPolicyInfo = todynamic(AutoSensitivityLabelPolicyInfo)