let parser=(disabled:bool=false) 
{
  ASimDnsActivityLogs  | where not(disabled)
  | extend
      EventStartTime = TimeGenerated,
      EventEndTime = TimeGenerated,
      EventSchema = "Dns",
      EventSchemaVersion="0.1.3"
  //  -- Aliases
  | extend
      Dvc = DvcHostname,
      DnsResponseCodeName=EventResultDetails,
      Domain=DnsQuery,
      IpAddr=SrcIpAddr,
      Src=SrcIpAddr,
      DvcHostname = SrcIpAddr,
      Duration = DnsNetworkDuration,
      Process = SrcProcessName,
      SessionId = DnsSessionId,
      User = SrcUsername,
      Hostname = SrcHostname
};
parser (disabled)