let parser=
(
  starttime:datetime=datetime(null), 
  endtime:datetime=datetime(null),
  srcipaddr:string='*',
  domain_has_any:dynamic=dynamic([]),
  responsecodename:string='*', 
  response_has_ipv4:string='*',
  response_has_any_prefix:dynamic=dynamic([]),
  eventtype:string='Query',
  disabled:bool=false
)
{
  ASimDnsActivityLogs  | where not(disabled)
  //  -- Pre-parsing filtering:
  | where
      (response_has_ipv4=='*') and (array_length(response_has_any_prefix) == 0) // -- Check that unsupported filters are set to default
      and (isnull(starttime) or TimeGenerated >= starttime)
      and (isnull(endtime) or TimeGenerated <= endtime)
      and (srcipaddr=='*' or SrcIpAddr==srcipaddr)
      and (array_length(domain_has_any) ==0 or DnsQuery has_any (domain_has_any))
      and (responsecodename=='*' or EventResultDetails == responsecodename)
      and (eventtype == "*" or eventtype == EventType or (eventtype == "lookup" and EventType == "Query")) // -- Support "lookup" as value for backward compatibility
  // --
  | project-rename
      EventUid = _ItemId
  | extend
      EventStartTime = TimeGenerated,
      EventEndTime = TimeGenerated,
      Dvc = coalesce (Dvc, DvcFQDN, DvcHostname, DvcIpAddr, DvcId, _ResourceId, strcat (EventVendor,'/', EventProduct)),
      Dst = coalesce (DstFQDN, DstHostname, DstIpAddr, DstDvcId),
      Src = coalesce (SrcFQDN, SrcHostname, SrcIpAddr, SrcDvcId),
      EventSchema = "Dns"
  // -- Type fixes
  | extend
      ThreatConfidence = toint(ThreatConfidence),
      ThreatFirstReportedTime = todatetime(ThreatFirstReportedTime),
      ThreatIsActive = tobool(ThreatIsActive),
      ThreatLastReportedTime = todatetime(ThreatLastReportedTime),
      ThreatOriginalRiskLevel = tostring(ThreatOriginalRiskLevel),
      ThreatRiskLevel = toint(ThreatRiskLevel)
  //  -- Aliases here
  | extend
      DnsResponseCodeName=EventResultDetails,
      Domain=DnsQuery,
      IpAddr=SrcIpAddr,
      SessionId=DnsSessionId,
      Duration = DnsNetworkDuration,
      Process = SrcProcessName,
      User = SrcUsername,
      Hostname = SrcHostname,
      DvcScopeId = coalesce(DvcScopeId,_SubscriptionId)
    | project-away
        TenantId, SourceSystem, _ResourceId, _SubscriptionId
};
parser (starttime=starttime, endtime=endtime, srcipaddr=srcipaddr, domain_has_any=domain_has_any, responsecodename=responsecodename, response_has_ipv4=response_has_ipv4, response_has_any_prefix=response_has_any_prefix, eventtype=eventtype, disabled=disabled)
