source 
| project
    TimeGenerated = todatetime(TimeGenerated),
    FeatureFlagReference = FeatureFlagReference,
    FeatureName = FeatureName,
    AllocationId = AllocationId,
    Variant = Variant,
    VariantAssignmentPercentage = toreal(VariantAssignmentPercentage),
    IsControlVariant = tobool(IsControlVariant),
    AssignmentEventCount = tolong(AssignmentEventCount),
    MinTimeGenerated = todatetime(MinTimeGenerated),
    MaxTimeGenerated = todatetime(MaxTimeGenerated),
    BinStartTime = todatetime(BinStartTime),
    BinSize = tolong(BinSize)